CREATE DATABASE QLVLXD
USE QLVLXD 

create table NHANVIEN(
	MANV INT IDENTITY(1,1) not null,
	TENNV nvarchar(250),
	SDT INT,
	DIACHI NVARCHAR(1000),
	LAOINV INT,
	TRANGTHAI INT,
	TENDANGNHAP VARCHAR(250),
	MATKHAU VARCHAR(250)
					);

create table NHACC(
	MANCC INT IDENTITY(1,1) not null,
	TENNCC nvarchar(250),
	SDT INT,
	DIACHI NVARCHAR(1000)
					);

create table KHACHHANG(
	MAKH INT IDENTITY(1,1) not null,
	TENKH nvarchar(250),
	SDT INT,
	DIACHI NVARCHAR(1000)
					);

create table LOAIHANGHOA(
	MALOAI INT IDENTITY(1,1) not null,
	TENLOAI nvarchar(250),
	
					);
create table HANGHOA(
	MAHH INT IDENTITY(1,1) not null,
	TENHH nvarchar(250),
	SOLUONGTON INT,
	GIANHAP INT,
	DONGIA INT,
	LOAIHANG INT,
	DONVITINH NVARCHAR(250)
					);
	


create table PHIEUNHAP(
	SOPN INT IDENTITY(1,1) not null,
	MANCC INT,
	NGAYNHAP DATETIME,
	TONGTIEN INT,
	NVLAP INT
					);

create table CHITIETPN(
	SOPN INT not null,
	MAHH INT NOT NULL,
	SOLUONGNHAP INT
					);
create table HOADON(
	SOHD INT IDENTITY(1,1) not null,
	TONGTIEN INT,
	NGAYLAP DATETIME,
	MAKH INT,
	NVLAP INT
					);

create table CTHOADON(
	SOHD INT  not null,
	MAHH INT NOT NULL,
	SOLUONG INT
					);

-- CREATE KEY
ALTER TABLE NHANVIEN
ADD 
	CONSTRAINT PK_NV PRIMARY KEY(MANV)

ALTER TABLE NHACC
ADD 
	CONSTRAINT PK_NCC PRIMARY KEY(MANCC)

ALTER TABLE KHACHHANG
ADD 
	CONSTRAINT PK_KH PRIMARY KEY(MAKH)

ALTER TABLE LOAIHANGHOA
ADD 
	CONSTRAINT PK_LHH PRIMARY KEY(MALOAI)

ALTER TABLE HANGHOA
ADD 
	CONSTRAINT PK_HH PRIMARY KEY(MAHH),
	CONSTRAINT FK_HH_LHH foreign key(LOAIHANG) REFERENCES LOAIHANGHOA(MALOAI)

ALTER TABLE PHIEUNHAP
ADD 
	CONSTRAINT PK_PN PRIMARY KEY(SOPN),
	CONSTRAINT FK_PN_NCC foreign key(MANCC) REFERENCES NHACC(MANCC),
	CONSTRAINT FK_PN_nv foreign key(NVLAP) REFERENCES NHANVIEN(MANV)

ALTER TABLE CHITIETPN
ADD 
	CONSTRAINT PK_CTPN PRIMARY KEY(SOPN, MAHH),
	CONSTRAINT FK_PN_CTPN foreign key(SOPN) REFERENCES PHIEUNHAP(SOPN),
	CONSTRAINT FK_PN_HH foreign key(MAHH) REFERENCES HANGHOA(MAHH)

ALTER TABLE HOADON
ADD 
	CONSTRAINT PK_HD PRIMARY KEY(SOHD),
	CONSTRAINT FK_HD_KH foreign key(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_PN_HD foreign key(NVLAP) REFERENCES NHANVIEN(MANV)

ALTER TABLE CTHOADON
ADD 
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MAHH),
	CONSTRAINT FK_CTHD_HD foreign key(SOHD) REFERENCES HOADON(SOHD),
	CONSTRAINT FK_CTHD_HH foreign key(MAHH) REFERENCES HANGHOA(MAHH)

